detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  LongParameterList:
    max_params: 4
  NestedIterators:
    max_allowed_nesting: 2
  TooManyStatements:
    max_statements: 10
  UncommunicativeMethodName:
    accept: ['sha1']
  UncommunicativeParameterName:
    accept: ['_', 'x', 'y', 'sha1', 'db']
  UncommunicativeVariableName:
    accept: ['_', 'e', 'k', 'v', 'x', 'y', 'sha1', 'db']
  UtilityFunction:
    public_methods_only: true
